window.QUIZ_QUESTIONS = [
  {category:"Figuren",difficulty:"leicht",question:"Wie heißt Harrys Eule?",answers:["Hedwig","Errol","Fawkes","Pigwidgeon"],correct:0},
  {category:"Figuren",difficulty:"leicht",question:"Wer ist Harrys bester Freund aus der Familie Weasley?",answers:["Percy","Ron","Fred","Charlie"],correct:1},
  {category:"Hogwarts",difficulty:"leicht",question:"In welchem Haus ist Harry Potter?",answers:["Ravenclaw","Hufflepuff","Gryffindor","Slytherin"],correct:2},
  {category:"Zaubersprüche",difficulty:"leicht",question:"Welcher Zauberspruch öffnet Türen?",answers:["Alohomora","Lumos","Nox","Accio"],correct:0},
  {category:"Orte",difficulty:"leicht",question:"Wie heißt die magische Einkaufsstraße in London?",answers:["Ligusterweg","Winkelgasse","Spinner's End","Godric's Hollow"],correct:1},
  {category:"Objekte",difficulty:"leicht",question:"Welches Spiel wird auf Besen gespielt?",answers:["Zauberschach","Quidditch","Gobstones","Exploding Snap"],correct:1},
  {category:"Figuren",difficulty:"mittel",question:"Wie heißt Hermines Katze?",answers:["Mrs Norris","Krummbein","Trevor","Arnold"],correct:1},
  {category:"Hogwarts",difficulty:"mittel",question:"Wer unterrichtet im ersten Schuljahr Zaubertränke?",answers:["Severus Snape","Remus Lupin","Filius Flitwick","Pomona Sprout"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Was zeigt der Spiegel Nerhegeb?",answers:["Die Zukunft","Den größten Wunsch","Den wahren Namen","Versteckte Räume"],correct:1},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Spruch ruft Gegenstände herbei?",answers:["Accio","Expelliarmus","Stupefy","Reparo"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Welcher Animagus verwandelt sich in einen schwarzen Hund?",answers:["James Potter","Peter Pettigrew","Sirius Black","Minerva McGonagall"],correct:2},
  {category:"Orte",difficulty:"mittel",question:"In welchem Dorf liegt der Pub Drei Besen?",answers:["Hogsmeade","Ottery St Catchpole","Little Hangleton","Tinworth"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welche Pflanze schreit beim Umtopfen?",answers:["Teufelsschlinge","Mandragora","Mimbulus Mimbletonia","Flussgras"],correct:1},
  {category:"Objekte",difficulty:"mittel",question:"Womit wird der Eingang zur Kammer des Schreckens geöffnet?",answers:["Parseltongue","Ein Portschlüssel","Ein Zauberstabkern","Flohpulver"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Wie heißt Rons Ratte wirklich?",answers:["Barty Crouch","Peter Pettigrew","Igor Karkaroff","Stan Shunpike"],correct:1},
  {category:"Orte",difficulty:"schwer",question:"Woher bekommen Harry, Ron und Hermine viele Schulbücher?",answers:["Flourish and Blotts","Honeydukes","Gringotts","Eeylops"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauber erzeugt einen Patronus?",answers:["Expecto Patronum","Protego Maxima","Finite Incantatem","Riddikulus"],correct:0},
  {category:"Hogwarts",difficulty:"schwer",question:"Wer ist Hauslehrer von Ravenclaw?",answers:["Filius Flitwick","Sybill Trelawney","Cuthbert Binns","Horace Slughorn"],correct:0},
  {category:"Objekte",difficulty:"schwer",question:"Welcher Kern steckt in Harrys Zauberstab?",answers:["Drachenherzfaser","Einhornhaar","Phönixfeder","Thestralschweifhaar"],correct:2},
  {category:"Figuren",difficulty:"schwer",question:"Wer gibt Harry im ersten Jahr den Tarnumhang?",answers:["Dumbledore","Sirius Black","Hagrid","Remus Lupin"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Wie heißt das Haus der Familie Black in London?",answers:["Grimmauldplatz 12","Ligusterweg 4","Spinner's End","Fuchsbau"],correct:0},
  {category:"Figuren",difficulty:"leicht",question:"Wer ist der Schulleiter von Hogwarts zu Harrys Schulbeginn?",answers:["Albus Dumbledore","Cornelius Fudge","Gilderoy Lockhart","Argus Filch"],correct:0},
  {category:"Hogwarts",difficulty:"leicht",question:"Welches Fach unterrichtet Professor Flitwick?",answers:["Verwandlung","Kräuterkunde","Zauberkunst","Astronomie"],correct:2},
  {category:"Objekte",difficulty:"mittel",question:"Wie heißt die Zeitung der Zaubererwelt?",answers:["Tagesprophet","Klitterer","Hexenwoche","Magisches Register"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Spruch repariert Gegenstände?",answers:["Reparo","Reducio","Diffindo","Obliviate"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wie heißt Nevilles Kröte?",answers:["Trevor","Scabbers","Arnold","Crookshanks"],correct:0},
  {category:"Orte",difficulty:"leicht",question:"Wie heißt das Zuhause der Weasleys?",answers:["Der Fuchsbau","Malfoy Manor","Shell Cottage","Nurmengard"],correct:0},
  {category:"Hogwarts",difficulty:"schwer",question:"Welche Position spielt Harry im Quidditch-Team?",answers:["Jäger","Sucher","Treiber","Hüter"],correct:1},
  {category:"Objekte",difficulty:"schwer",question:"Was ist ein Horkrux?",answers:["Ein Schutzzauber","Ein Seelenteil in einem Objekt","Ein magisches Tier","Ein Zaubertrank"],correct:1},
  {category:"Figuren",difficulty:"schwer",question:"Wer ist der Halbblutprinz?",answers:["Severus Snape","Tom Riddle","Draco Malfoy","Regulus Black"],correct:0},
  {category:"Figuren",difficulty:"leicht",question:"Wie heißt Harrys Patentante?",answers:["Petunia","Marge","Molly","Minerva"],correct:0},
  {category:"Figuren",difficulty:"leicht",question:"Wie heißt Harrys Cousin?",answers:["Dudley","Dean","Dennis","Dobby"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer ist Rons jüngere Schwester?",answers:["Ginny","Fleur","Angelina","Katie"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer leitet die Schülerzeitung Der Klitterer?",answers:["Xenophilius Lovegood","Rita Kimmkorn","Arthur Weasley","Amos Diggory"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Wie heißt der Bruder von Sirius Black?",answers:["Regulus","Rabastan","Rufus","Rodolphus"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Wer ist die Mutter von Draco Malfoy?",answers:["Narzissa","Bellatrix","Andromeda","Alecto"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer ist der Wildhüter von Hogwarts?",answers:["Hagrid","Filch","Bane","Firenze"],correct:0},
  {category:"Figuren",difficulty:"leicht",question:"Wie heißt der Hauself der Familie Malfoy?",answers:["Dobby","Kreacher","Winky","Hokey"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Welcher Lehrer ist ein Werwolf?",answers:["Remus Lupin","Severus Snape","Quirinus Quirrell","Gilderoy Lockhart"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Wer gibt sich im vierten Jahr als Moody aus?",answers:["Barty Crouch Jr.","Lucius Malfoy","Peter Pettigrew","Igor Karkaroff"],correct:0},
  {category:"Hogwarts",difficulty:"leicht",question:"Welches Haus ist für Schlauheit und Ehrgeiz bekannt?",answers:["Slytherin","Hufflepuff","Gryffindor","Ravenclaw"],correct:0},
  {category:"Hogwarts",difficulty:"leicht",question:"Welches Haus ist für Fleiß und Loyalität bekannt?",answers:["Hufflepuff","Ravenclaw","Slytherin","Gryffindor"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welcher Geist gehört zu Gryffindor?",answers:["Fast Kopfloser Nick","Graue Dame","Blutiger Baron","Fetter Mönch"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welcher Geist gehört zu Ravenclaw?",answers:["Graue Dame","Fast Kopfloser Nick","Peeves","Fetter Mönch"],correct:0},
  {category:"Hogwarts",difficulty:"schwer",question:"Wie heißt der Poltergeist von Hogwarts?",answers:["Peeves","Binns","Firenze","Griphook"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Wer verwaltet die Bibliothek von Hogwarts?",answers:["Madam Pince","Madam Pomfrey","Professor Sinistra","Professor Vector"],correct:0},
  {category:"Hogwarts",difficulty:"leicht",question:"Wer kümmert sich um verletzte Schüler?",answers:["Madam Pomfrey","Madam Hooch","Madam Malkin","Madam Rosmerta"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welches Fach unterrichtet Professor Sprout?",answers:["Kräuterkunde","Zauberkunst","Astronomie","Arithmantik"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welches Fach unterrichtet Professor Trelawney?",answers:["Wahrsagen","Verteidigung","Alte Runen","Zaubertränke"],correct:0},
  {category:"Hogwarts",difficulty:"schwer",question:"Welches magische Artefakt teilt Schüler in Häuser ein?",answers:["Sprechender Hut","Feuerkelch","Denkarium","Stein der Weisen"],correct:0},
  {category:"Zaubersprüche",difficulty:"leicht",question:"Welcher Spruch macht Licht?",answers:["Lumos","Nox","Aguamenti","Wingardium Leviosa"],correct:0},
  {category:"Zaubersprüche",difficulty:"leicht",question:"Welcher Spruch löscht Licht?",answers:["Nox","Lumos","Incendio","Accio"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Spruch entwaffnet Gegner?",answers:["Expelliarmus","Stupefy","Protego","Petrificus Totalus"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Spruch betäubt?",answers:["Stupefy","Riddikulus","Reparo","Alohomora"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Spruch schützt wie ein Schild?",answers:["Protego","Accio","Diffindo","Obliviate"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Spruch vertreibt einen Irrwicht?",answers:["Riddikulus","Expecto Patronum","Imperio","Confundo"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Spruch lässt Wasser erscheinen?",answers:["Aguamenti","Incendio","Glacius","Lumos"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Spruch verändert Erinnerungen?",answers:["Obliviate","Reparo","Levioso","Sectumsempra"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Spruch lässt Gegenstände schweben?",answers:["Wingardium Leviosa","Accio","Nox","Protego"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Spruch kann Dinge zerschneiden?",answers:["Diffindo","Stupefy","Alohomora","Finite"],correct:0},
  {category:"Orte",difficulty:"leicht",question:"Wo wohnen Harrys Verwandte?",answers:["Ligusterweg 4","Grimmauldplatz 12","Spinner's End","Fuchsbau"],correct:0},
  {category:"Orte",difficulty:"leicht",question:"Welche Bank gibt es in der Winkelgasse?",answers:["Gringotts","Honeydukes","Ollivanders","Borgin und Burkes"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Wo kaufen Schüler Zauberstäbe?",answers:["Ollivanders","Madam Malkin","Eeylops","Flourish and Blotts"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Wie heißt der Laden für Süßigkeiten in Hogsmeade?",answers:["Honeydukes","Zonko","Drei Besen","Eberkopf"],correct:0},
  {category:"Orte",difficulty:"schwer",question:"Wie heißt das Dorf, in dem Harrys Eltern lebten?",answers:["Godric's Hollow","Hogsmeade","Little Hangleton","Ottery St Catchpole"],correct:0},
  {category:"Orte",difficulty:"schwer",question:"Wo steht das Haus der Malfoys?",answers:["Malfoy Manor","Shell Cottage","Nurmengard","Spinner's End"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Wie heißt der verbotene Wald bei Hogwarts?",answers:["Verbotener Wald","Dunkler Wald","Nordwald","Schwarzwald"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Welcher Pub führt zur Winkelgasse?",answers:["Tropfender Kessel","Drei Besen","Eberkopf","Schweinskopf"],correct:0},
  {category:"Orte",difficulty:"schwer",question:"Wo lebt Bill Weasley später mit Fleur?",answers:["Shell Cottage","Fuchsbau","Grimmauldplatz 12","Hogsmeade"],correct:0},
  {category:"Orte",difficulty:"schwer",question:"Welche Zaubererstraße ist für dunkle Läden bekannt?",answers:["Nocturngasse","Winkelgasse","Charing Cross Road","Horizontallee"],correct:0},
  {category:"Objekte",difficulty:"leicht",question:"Was bringt Harry zu Beginn nach Hogwarts?",answers:["Brief","Denkarium","Feuerkelch","Zeitumkehrer"],correct:0},
  {category:"Objekte",difficulty:"leicht",question:"Was macht ein Tarnumhang?",answers:["Unsichtbar machen","Fliegen lassen","Zeit drehen","Erinnerungen zeigen"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Welches Objekt wählt im vierten Jahr die Champions aus?",answers:["Feuerkelch","Sprechender Hut","Denkarium","Erinnermich"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Womit reist man durch Kamine?",answers:["Flohpulver","Portschlüssel","Besenwachs","Drachenblut"],correct:0},
  {category:"Objekte",difficulty:"schwer",question:"Worin bewahrt Dumbledore Erinnerungen auf?",answers:["Denkarium","Deluminator","Feuerkelch","Erinnermich"],correct:0},
  {category:"Objekte",difficulty:"schwer",question:"Welches Objekt hilft Hermine bei ihrem Stundenplan?",answers:["Zeitumkehrer","Marauderkarte","Tarnumhang","Deluminator"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Was zeigt die Karte des Rumtreibers?",answers:["Menschen in Hogwarts","Zukunft","Hauspunkte","Zauberstabkerne"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Stein soll Leben verlängern und Metall verwandeln können?",answers:["Stein der Weisen","Auferstehungsstein","Mondstein","Bezoar"],correct:0},
  {category:"Objekte",difficulty:"schwer",question:"Welches Objekt kann Lichter einfangen?",answers:["Deluminator","Erinnermich","Denkarium","Portschlüssel"],correct:0},
  {category:"Objekte",difficulty:"schwer",question:"Welches Objekt nutzt Hermine im dritten Jahr, um Zeit zu gewinnen?",answers:["Zeitumkehrer","Horkrux","Medaillon","Erinnermich"],correct:0},
  {category:"Wesen",difficulty:"leicht",question:"Welches Wesen zieht die Hogwarts-Kutschen und ist nur für manche sichtbar?",answers:["Thestral","Hippogreif","Einhorn","Kneazle"],correct:0},
  {category:"Wesen",difficulty:"leicht",question:"Wie heißt Hagrids Hippogreif?",answers:["Seidenschnabel","Aragog","Norbert","Fang"],correct:0},
  {category:"Wesen",difficulty:"mittel",question:"Welche Spinne lebt im Verbotenen Wald?",answers:["Aragog","Nagini","Norbert","Grawp"],correct:0},
  {category:"Wesen",difficulty:"mittel",question:"Was für ein Wesen ist Fawkes?",answers:["Phönix","Drache","Hippogreif","Kneazle"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Welche Schlangenart ist Nagini?",answers:["Schlange","Basilisk","Ashwinder","Runespoor"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen bewacht oft wertvolle Dinge in Gringotts?",answers:["Drache","Thestral","Dementor","Kappa"],correct:0},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen saugt gute Gefühle aus Menschen?",answers:["Dementor","Inferius","Pixie","Bowtruckle"],correct:0},
  {category:"Wesen",difficulty:"mittel",question:"Was für ein Wesen ist Norbert?",answers:["Drache","Eule","Hund","Ratte"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Welche Wesen leben im See bei Hogwarts?",answers:["Wassermenschen","Thestrale","Hauselfen","Doxys"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Was für ein Wesen ist Firenze?",answers:["Zentaur","Riese","Hauself","Kobold"],correct:0},
  {category:"Figuren",difficulty:"leicht",question:"Wer ist Harrys erste Freundin aus Ravenclaw?",answers:["Cho Chang","Luna Lovegood","Padma Patil","Katie Bell"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer ist Lunas Vater?",answers:["Xenophilius Lovegood","Amos Diggory","Arthur Weasley","Aberforth Dumbledore"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer arbeitet im Zaubereiministerium in der Abteilung gegen Muggelartefakte?",answers:["Arthur Weasley","Lucius Malfoy","Cornelius Fudge","Rufus Scrimgeour"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Wer ist der Bruder von Albus Dumbledore?",answers:["Aberforth","Aurelius","Antioch","Armando"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Wer war Schulleiter vor Dumbledore?",answers:["Armando Dippet","Phineas Nigellus","Horace Slughorn","Elphias Doge"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wie heißt Cedric Diggorys Haus?",answers:["Hufflepuff","Ravenclaw","Gryffindor","Slytherin"],correct:0},
  {category:"Figuren",difficulty:"leicht",question:"Wer ist Harrys Quidditch-Kapitänin im ersten Team?",answers:["Oliver Wood","Angelina Johnson","Katie Bell","Alicia Spinnet"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer betreibt den Eberkopf in Hogsmeade?",answers:["Aberforth Dumbledore","Madam Rosmerta","Tom","Horace Slughorn"],correct:0},
  {category:"Hogwarts",difficulty:"leicht",question:"Wie gelangen Erstklässler traditionell zum Schloss?",answers:["Mit Booten","Mit Besen","Mit Flohpulver","Mit Portschlüssel"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welches Fach unterrichtet Madam Hooch?",answers:["Flugunterricht","Zauberkunst","Kräuterkunde","Verwandlung"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Wie heißt der Hausmeister von Hogwarts?",answers:["Argus Filch","Rubeus Hagrid","Cuthbert Binns","Filius Flitwick"],correct:0},
  {category:"Hogwarts",difficulty:"schwer",question:"Welche Katze gehört Argus Filch?",answers:["Mrs Norris","Krummbein","Mrs Figg","Hokey"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welcher Raum erscheint, wenn man ihn wirklich braucht?",answers:["Raum der Wünsche","Kammer des Schreckens","Gemeinschaftsraum","Astronomieturm"],correct:0},
  {category:"Hogwarts",difficulty:"schwer",question:"Wie heißt die Geisterlehrkraft für Geschichte der Zauberei?",answers:["Cuthbert Binns","Filius Flitwick","Bathilda Bagshot","Phineas Nigellus"],correct:0},
  {category:"Zaubersprüche",difficulty:"leicht",question:"Welcher Spruch macht Feuer?",answers:["Incendio","Aguamenti","Nox","Reparo"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Spruch lässt einen Gegner erstarren?",answers:["Petrificus Totalus","Lumos Maxima","Aguamenti","Reducio"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Spruch beendet viele Zauberwirkungen?",answers:["Finite Incantatem","Alohomora","Accio","Riddikulus"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher unverzeihliche Fluch kontrolliert andere Menschen?",answers:["Imperio","Crucio","Avada Kedavra","Sectumsempra"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher unverzeihliche Fluch verursacht große Schmerzen?",answers:["Crucio","Imperio","Obliviate","Confundo"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauber ist als Tötungsfluch bekannt?",answers:["Avada Kedavra","Stupefy","Expelliarmus","Reducto"],correct:0},
  {category:"Orte",difficulty:"leicht",question:"An welchem Bahnhof fährt der Hogwarts-Express ab?",answers:["King's Cross","Paddington","Victoria","Waterloo"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Welches Gleis führt zum Hogwarts-Express?",answers:["9 3/4","7 1/2","10 1/4","13"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Wie heißt das Zauberergefängnis?",answers:["Askaban","Nurmengard","Gringotts","Durmstrang"],correct:0},
  {category:"Orte",difficulty:"schwer",question:"Welche Schule nimmt am Trimagischen Turnier teil und reist mit einem Schiff an?",answers:["Durmstrang","Beauxbatons","Ilvermorny","Castelobruxo"],correct:0},
  {category:"Orte",difficulty:"schwer",question:"Welche Schule reist im vierten Jahr mit einer fliegenden Kutsche an?",answers:["Beauxbatons","Durmstrang","Ilvermorny","Mahoutokoro"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Wo liegt der Gemeinschaftsraum von Gryffindor?",answers:["Hinter dem Porträt der Fetten Dame","Neben der Großen Halle","Unter dem See","In der Bibliothek"],correct:0},
  {category:"Objekte",difficulty:"leicht",question:"Was braucht jeder Zauberer meistens zum Zaubern?",answers:["Zauberstab","Denkarium","Besen","Kessel"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Ball muss beim Quidditch vom Sucher gefangen werden?",answers:["Goldener Schnatz","Quaffel","Klatscher","Koboldball"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Ball wird beim Quidditch durch die Torringe geworfen?",answers:["Quaffel","Schnatz","Klatscher","Bludger"],correct:0},
  {category:"Objekte",difficulty:"schwer",question:"Welche Kugel erinnert Neville an Vergessenes?",answers:["Erinnermich","Deluminator","Denkarium","Zeitumkehrer"],correct:0},
  {category:"Objekte",difficulty:"schwer",question:"Welches dunkle Buch antwortet schriftlich?",answers:["Tom Riddles Tagebuch","Monsterbuch","Zaubertränke für Fortgeschrittene","Märchen von Beedle"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Besen ist Harrys erster eigener Rennbesen?",answers:["Nimbus 2000","Feuerblitz","Sauberwisch 7","Komet 260"],correct:0},
  {category:"Wesen",difficulty:"leicht",question:"Welches Haustier besitzt Neville?",answers:["Kröte","Eule","Katze","Ratte"],correct:0},
  {category:"Wesen",difficulty:"mittel",question:"Welche kleinen Wesen sorgen in Lockharts Unterricht für Chaos?",answers:["Cornish Pixies","Doxys","Bowtruckles","Niffler"],correct:0},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen bewacht im ersten Jahr eine Falltür?",answers:["Dreiköpfiger Hund","Basilisk","Troll","Drache"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Wie heißt Hagrids dreiköpfiger Hund?",answers:["Fluffy","Fang","Aragog","Norbert"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Was ist Grawp?",answers:["Riese","Zentaur","Drache","Hauself"],correct:0},
  {category:"Wesen",difficulty:"mittel",question:"Welche Wesen arbeiten in Gringotts?",answers:["Kobolde","Hauselfen","Zentauren","Dementoren"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen wird von einem Basiliskenblick versteinert, wenn man ihn indirekt sieht?",answers:["Menschen","Dementoren","Hauselfen","Thestrale"],correct:0},
  {category:"Figuren",difficulty:"leicht",question:"Wer ist der Vater von Ron Weasley?",answers:["Arthur Weasley","Bill Weasley","Percy Weasley","Charlie Weasley"],correct:0},
  {category:"Figuren",difficulty:"leicht",question:"Wer ist die Mutter von Ron Weasley?",answers:["Molly Weasley","Narzissa Malfoy","Petunia Dursley","Andromeda Tonks"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur kann besonders gut mit Tieren umgehen?",answers:["Rubeus Hagrid","Argus Filch","Gilderoy Lockhart","Cornelius Fudge"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer ist der Vater von Cedric Diggory?",answers:["Amos Diggory","Arthur Weasley","Barty Crouch","Ludo Bagman"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Wer war ein Todesser und Vater von Draco?",answers:["Lucius Malfoy","Igor Karkaroff","Rufus Scrimgeour","Ludo Bagman"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Welche Figur schreibt reißerische Artikel über Harry?",answers:["Rita Kimmkorn","Bathilda Bagshot","Madam Pince","Molly Weasley"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer ist der Zaubereiminister zu Beginn der Reihe?",answers:["Cornelius Fudge","Rufus Scrimgeour","Kingsley Shacklebolt","Barty Crouch"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Wer wird nach Fudge Zaubereiminister?",answers:["Rufus Scrimgeour","Arthur Weasley","Lucius Malfoy","Alastor Moody"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wie heißt Tonks mit Vornamen?",answers:["Nymphadora","Narzissa","Arabella","Ariana"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Welche Figur ist ein Metamorphmagus?",answers:["Nymphadora Tonks","Luna Lovegood","Ginny Weasley","Cho Chang"],correct:0},
  {category:"Hogwarts",difficulty:"leicht",question:"Wo essen die Schüler in Hogwarts gemeinsam?",answers:["Große Halle","Bibliothek","Astronomieturm","Eulerei"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welche Tür bewacht die Fette Dame?",answers:["Gryffindor-Gemeinschaftsraum","Slytherin-Gemeinschaftsraum","Bibliothek","Krankenflügel"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Wo werden verletzte Schüler versorgt?",answers:["Krankenflügel","Eulerei","Verwandlungsraum","Trophäenzimmer"],correct:0},
  {category:"Hogwarts",difficulty:"schwer",question:"Wo treffen sich Harrys Freunde heimlich zum Üben?",answers:["Raum der Wünsche","Eulerei","Zaubertrank-Klassenzimmer","Astronomieturm"],correct:0},
  {category:"Hogwarts",difficulty:"schwer",question:"Was befindet sich unter Hogwarts?",answers:["Die Kammer des Schreckens","Askaban","Gringotts","Der Fuchsbau"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welches Fach beschäftigt sich mit Sternen und Planeten?",answers:["Astronomie","Arithmantik","Alte Runen","Wahrsagen"],correct:0},
  {category:"Zaubersprüche",difficulty:"leicht",question:"Welcher Spruch ruft Licht aus dem Zauberstab?",answers:["Lumos","Nox","Reparo","Accio"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Spruch löscht den Lichtzauber?",answers:["Nox","Lumos","Incendio","Confundo"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Spruch verwirrt das Ziel?",answers:["Confundo","Reparo","Accio","Aguamenti"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Spruch verkleinert etwas?",answers:["Reducio","Engorgio","Diffindo","Protego"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Spruch vergrößert etwas?",answers:["Engorgio","Reducio","Nox","Finite"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Spruch lässt eine Tür aufgehen?",answers:["Alohomora","Stupefy","Petrificus Totalus","Riddikulus"],correct:0},
  {category:"Orte",difficulty:"leicht",question:"Wo kauft Harry seinen ersten Zauberstab?",answers:["Ollivanders","Honeydukes","Gringotts","Zonko"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Welche Gasse ist mit der Winkelgasse verbunden und düsterer?",answers:["Nocturngasse","Ligusterweg","Grimmauldplatz","Spinner's End"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Wo steht der Eberkopf?",answers:["Hogsmeade","Winkelgasse","Little Hangleton","Godric's Hollow"],correct:0},
  {category:"Orte",difficulty:"schwer",question:"Wo wächst Tom Riddle als Kind auf?",answers:["Waisenhaus","Fuchsbau","Malfoy Manor","Shell Cottage"],correct:0},
  {category:"Orte",difficulty:"schwer",question:"Wo liegt das Grab von Harrys Eltern?",answers:["Godric's Hollow","Hogsmeade","Little Whinging","Ottery St Catchpole"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Wo schlafen die Schüler von Gryffindor?",answers:["In Schlafsälen im Turm","In der Großen Halle","In der Bibliothek","Im Krankenflügel"],correct:0},
  {category:"Objekte",difficulty:"leicht",question:"Welcher Gegenstand gehört zum Quidditch und ist sehr klein?",answers:["Goldener Schnatz","Quaffel","Klatscher","Besenwachs"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Welches Objekt zeigt Harry, was er sich am meisten wünscht?",answers:["Spiegel Nerhegeb","Denkarium","Marauderkarte","Erinnermich"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Welches Buch beißt und schnappt nach Lesern?",answers:["Monsterbuch der Monster","Tom Riddles Tagebuch","Märchen von Beedle","Schulgeschichte Hogwarts"],correct:0},
  {category:"Objekte",difficulty:"schwer",question:"Welcher Gegenstand gehört zu den Heiligtümern des Todes?",answers:["Elderstab","Feuerkelch","Erinnermich","Quaffel"],correct:0},
  {category:"Objekte",difficulty:"schwer",question:"Welcher Stein gehört zu den Heiligtümern des Todes?",answers:["Auferstehungsstein","Stein der Weisen","Mondstein","Bezoar"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Was kann ein Portschlüssel bewirken?",answers:["Menschen an einen anderen Ort bringen","Türen öffnen","Licht erzeugen","Erinnerungen zeigen"],correct:0},
  {category:"Wesen",difficulty:"leicht",question:"Welches Wesen ist halb Pferd und halb Mensch?",answers:["Zentaur","Hippogreif","Kobold","Dementor"],correct:0},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen ist halb Adler und halb Pferd?",answers:["Hippogreif","Zentaur","Phönix","Thestral"],correct:0},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen kann aus seiner Asche neu entstehen?",answers:["Phönix","Drache","Basilisk","Niffler"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen lebt in der Kammer des Schreckens?",answers:["Basilisk","Hippogreif","Thestral","Zentaur"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Welche Wesen bewachen zeitweise Askaban?",answers:["Dementoren","Kobolde","Zentauren","Hauselfen"],correct:0},
  {category:"Figuren",difficulty:"leicht",question:"Wer ist Harrys Mutter?",answers:["Lily Potter","Petunia Dursley","Molly Weasley","Narzissa Malfoy"],correct:0},
  {category:"Figuren",difficulty:"leicht",question:"Wer ist Harrys Vater?",answers:["James Potter","Sirius Black","Remus Lupin","Severus Snape"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Welcher Freund von Harry wird später Werwolf-Lehrer?",answers:["Remus Lupin","Sirius Black","Peter Pettigrew","James Potter"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Wer verrät James und Lily an Voldemort?",answers:["Peter Pettigrew","Sirius Black","Remus Lupin","Severus Snape"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur ist auch als Wurmschwanz bekannt?",answers:["Peter Pettigrew","Sirius Black","Barty Crouch Jr.","Lucius Malfoy"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur ist auch als Tatze bekannt?",answers:["Sirius Black","James Potter","Remus Lupin","Peter Pettigrew"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur ist auch als Moony bekannt?",answers:["Remus Lupin","Sirius Black","James Potter","Peter Pettigrew"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Welche Figur ist auch als Krone bekannt?",answers:["James Potter","Sirius Black","Remus Lupin","Peter Pettigrew"],correct:0},
  {category:"Figuren",difficulty:"leicht",question:"Wie heißt Harrys Onkel?",answers:["Vernon Dursley","Arthur Weasley","Cornelius Fudge","Amos Diggory"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer unterrichtet Verwandlung in Harrys erstem Jahr?",answers:["Minerva McGonagall","Pomona Sprout","Filius Flitwick","Sybill Trelawney"],correct:0},
  {category:"Figuren",difficulty:"leicht",question:"Wer ist die Leiterin von Gryffindor?",answers:["Minerva McGonagall","Pomona Sprout","Sybill Trelawney","Madam Hooch"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer ist die Leiterin von Hufflepuff?",answers:["Pomona Sprout","Minerva McGonagall","Madam Pomfrey","Madam Pince"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Welcher Lehrer unterrichtet Geschichte der Zauberei?",answers:["Cuthbert Binns","Filius Flitwick","Horace Slughorn","Remus Lupin"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Wer bringt Harry im ersten Jahr zu seinem Verlies bei Gringotts?",answers:["Hagrid","Quirrell","Dumbledore","Ollivander"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer betreibt den Tropfenden Kessel?",answers:["Tom","Aberforth","Florean Fortescue","Ollivander"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Welche Figur ist eine Squib und Nachbarin der Dursleys?",answers:["Arabella Figg","Bathilda Bagshot","Madam Pince","Mafalda Hopkirk"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer ist der Vater von Luna Lovegood?",answers:["Xenophilius Lovegood","Amos Diggory","Arthur Weasley","Ted Tonks"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Welche Figur war Besitzerin von Hogwarts: Eine Geschichte?",answers:["Bathilda Bagshot","Rita Kimmkorn","Dolores Umbridge","Arabella Figg"],correct:0},
  {category:"Figuren",difficulty:"leicht",question:"Wer ist der Schulleiter von Durmstrang im vierten Jahr?",answers:["Igor Karkaroff","Olympe Maxime","Barty Crouch","Ludo Bagman"],correct:0},
  {category:"Figuren",difficulty:"leicht",question:"Wer leitet Beauxbatons im vierten Jahr?",answers:["Olympe Maxime","Minerva McGonagall","Dolores Umbridge","Madam Hooch"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer ist Direktorin von Beauxbatons?",answers:["Olympe Maxime","Madam Rosmerta","Sybill Trelawney","Pomona Sprout"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer kommentiert häufig Quidditch-Spiele in Hogwarts?",answers:["Lee Jordan","Dean Thomas","Seamus Finnigan","Colin Creevey"],correct:0},
  {category:"Figuren",difficulty:"leicht",question:"Wer fotografiert Harry oft in den ersten Schuljahren?",answers:["Colin Creevey","Dean Thomas","Lee Jordan","Cormac McLaggen"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer ist Harrys Quidditch-Rivale aus Slytherin?",answers:["Draco Malfoy","Blaise Zabini","Theodore Nott","Vincent Crabbe"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Wer ist ein Zentaur aus dem Verbotenen Wald?",answers:["Firenze","Griphook","Kreacher","Grawp"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wie heißt Hagrids Hund?",answers:["Fang","Fluffy","Norbert","Aragog"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Wie heißt Dumbledores Schwester?",answers:["Ariana","Kendra","Bathilda","Merope"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Wie heißt Dumbledores Mutter?",answers:["Kendra","Ariana","Narzissa","Merope"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Wie heißt Voldemorts Mutter?",answers:["Merope Gaunt","Ariana Dumbledore","Narzissa Malfoy","Bellatrix Lestrange"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Wie heißt Voldemorts Vater?",answers:["Tom Riddle Sr.","Morfin Gaunt","Marvolo Gaunt","Salazar Slytherin"],correct:0},
  {category:"Hogwarts",difficulty:"leicht",question:"Wie viele Häuser hat Hogwarts?",answers:["Vier","Drei","Fünf","Sieben"],correct:0},
  {category:"Hogwarts",difficulty:"leicht",question:"Welches Haus hat einen Löwen als Symbol?",answers:["Gryffindor","Slytherin","Ravenclaw","Hufflepuff"],correct:0},
  {category:"Hogwarts",difficulty:"leicht",question:"Welches Haus hat eine Schlange als Symbol?",answers:["Slytherin","Gryffindor","Ravenclaw","Hufflepuff"],correct:0},
  {category:"Hogwarts",difficulty:"leicht",question:"Welches Haus hat einen Dachs als Symbol?",answers:["Hufflepuff","Ravenclaw","Slytherin","Gryffindor"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welches Haus steht besonders für Klugheit?",answers:["Ravenclaw","Gryffindor","Slytherin","Hufflepuff"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welches Haus steht besonders für Mut?",answers:["Gryffindor","Hufflepuff","Ravenclaw","Slytherin"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welches Haus steht besonders für Ehrgeiz?",answers:["Slytherin","Gryffindor","Hufflepuff","Ravenclaw"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welches Haus steht besonders für Loyalität?",answers:["Hufflepuff","Slytherin","Ravenclaw","Gryffindor"],correct:0},
  {category:"Hogwarts",difficulty:"schwer",question:"Wie viele Treppen soll Hogwarts laut Fact File haben?",answers:["142","99","203","77"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"In welchem Landesteil liegt Hogwarts?",answers:["Schottische Highlands","Irische Küste","Walisische Berge","Englische Südküste"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Was verhindert Apparieren auf dem Hogwarts-Gelände?",answers:["Anti-Apparier-Zauber","Flohpulver","Der See","Der Sprechende Hut"],correct:0},
  {category:"Hogwarts",difficulty:"schwer",question:"Welche Eigenschaft hat Hogwarts auf Karten?",answers:["Es ist unortbar","Es wandert jede Nacht","Es ist immer unsichtbar","Es liegt unter Wasser"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welcher Ort gehört laut Fact File zu Hogwarts?",answers:["Astronomieturm","Nocturngasse","Malfoy Manor","Shell Cottage"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welcher Ort gehört laut Fact File zu Hogwarts?",answers:["Kerker","Gringotts","Askaban","Godric's Hollow"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welcher Ort gehört laut Fact File zu Hogwarts?",answers:["Bibliothek","Ollivanders","Honeydukes","Eberkopf"],correct:0},
  {category:"Hogwarts",difficulty:"leicht",question:"Welcher große Raum ist zentral für Feste in Hogwarts?",answers:["Große Halle","Eulerei","Kerker","Krankenflügel"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Wo befindet sich Hagrids Hütte?",answers:["Am Rand des Verbotenen Waldes","In Hogsmeade","Im Schlosskeller","Neben Gringotts"],correct:0},
  {category:"Hogwarts",difficulty:"schwer",question:"Welches Ereignis fand in Hogwarts statt?",answers:["Das Trimagische Turnier","Die Gründung von Gringotts","Die Eröffnung von Ollivanders","Die Wahl des Zaubereiministers"],correct:0},
  {category:"Hogwarts",difficulty:"schwer",question:"Welche Schlacht fand in Hogwarts statt?",answers:["Schlacht von Hogwarts","Schlacht von Askaban","Schlacht von Godric's Hollow","Schlacht von Hogsmeade"],correct:0},
  {category:"Zaubersprüche",difficulty:"leicht",question:"Welcher Zauber ist der Entwaffnungszauber?",answers:["Expelliarmus","Lumos","Nox","Reparo"],correct:0},
  {category:"Zaubersprüche",difficulty:"leicht",question:"Welcher Zauber ist der Aufrufezauber?",answers:["Accio","Alohomora","Nox","Riddikulus"],correct:0},
  {category:"Zaubersprüche",difficulty:"leicht",question:"Welcher Zauber ist der Lichtzauber?",answers:["Lumos","Nox","Reparo","Diffindo"],correct:0},
  {category:"Zaubersprüche",difficulty:"leicht",question:"Welcher Zauber beendet Lumos?",answers:["Nox","Lumos","Accio","Protego"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauber repariert etwas?",answers:["Reparo","Reducto","Diffindo","Stupefy"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauber öffnet Schlösser?",answers:["Alohomora","Imperio","Crucio","Morsmordre"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauber schützt vor Angriffen?",answers:["Protego","Accio","Nox","Incendio"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauber betäubt Gegner?",answers:["Stupefy","Lumos","Alohomora","Reparo"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauber lässt Wasser erscheinen?",answers:["Aguamenti","Incendio","Nox","Confundo"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauber lässt Flammen entstehen?",answers:["Incendio","Aguamenti","Reducio","Finite"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauber ruft das Dunkle Mal hervor?",answers:["Morsmordre","Sectumsempra","Riddikulus","Engorgio"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauber wurde vom Halbblutprinzen erfunden?",answers:["Sectumsempra","Accio","Nox","Alohomora"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauber gehört zu den Unverzeihlichen Flüchen?",answers:["Imperio","Lumos","Reparo","Aguamenti"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauber gehört zu den Unverzeihlichen Flüchen?",answers:["Crucio","Nox","Diffindo","Reparo"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauber gehört zu den Unverzeihlichen Flüchen?",answers:["Avada Kedavra","Accio","Protego","Lumos"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauber hilft gegen Dementoren?",answers:["Expecto Patronum","Morsmordre","Confundo","Reducio"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauber hilft gegen Irrwichte?",answers:["Riddikulus","Protego","Alohomora","Nox"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauber wird in der DA häufig geübt?",answers:["Expelliarmus","Morsmordre","Imperio","Avada Kedavra"],correct:0},
  {category:"Orte",difficulty:"leicht",question:"Welches Dorf liegt nahe bei Hogwarts?",answers:["Hogsmeade","Godric's Hollow","Little Whinging","Ottery St Catchpole"],correct:0},
  {category:"Orte",difficulty:"leicht",question:"Welcher Ort verbindet Muggel-London mit der Winkelgasse?",answers:["Tropfender Kessel","Eberkopf","Drei Besen","Honeydukes"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Welche Straße liegt im Muggel-London und führt zum Tropfenden Kessel?",answers:["Charing Cross Road","Baker Street","Privet Drive","King's Road"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Wo gibt es den Laden Honeydukes?",answers:["Hogsmeade","Winkelgasse","Nocturngasse","Godric's Hollow"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Wo gibt es den Scherzartikelladen Zonko?",answers:["Hogsmeade","Gringotts","Askaban","Shell Cottage"],correct:0},
  {category:"Orte",difficulty:"schwer",question:"Welcher Pub in Hogsmeade wird von Aberforth betrieben?",answers:["Eberkopf","Drei Besen","Tropfender Kessel","Honeydukes"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Welcher Pub in Hogsmeade ist besonders bekannt?",answers:["Drei Besen","Tropfender Kessel","Eberkopf","Nocturngasse"],correct:0},
  {category:"Orte",difficulty:"schwer",question:"Welcher Ort ist durch Kobolde und Verliese bekannt?",answers:["Gringotts","Ollivanders","Honeydukes","Zonko"],correct:0},
  {category:"Orte",difficulty:"schwer",question:"Welcher Ort ist das Zuhause der Dursleys?",answers:["Ligusterweg 4","Grimmauldplatz 12","Fuchsbau","Shell Cottage"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Welcher Ort ist Hauptsitz des Ordens des Phönix?",answers:["Grimmauldplatz 12","Ligusterweg 4","Hogsmeade","Winkelgasse"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Welcher Ort ist das Zuhause der Weasleys?",answers:["Fuchsbau","Malfoy Manor","Shell Cottage","Godric's Hollow"],correct:0},
  {category:"Orte",difficulty:"schwer",question:"Welcher Ort gehört Bill und Fleur?",answers:["Shell Cottage","Fuchsbau","Grimmauldplatz 12","Nocturngasse"],correct:0},
  {category:"Objekte",difficulty:"leicht",question:"Welcher Gegenstand teilt Schüler in Häuser ein?",answers:["Sprechender Hut","Denkarium","Feuerkelch","Erinnermich"],correct:0},
  {category:"Objekte",difficulty:"leicht",question:"Welcher Gegenstand macht unsichtbar?",answers:["Tarnumhang","Zeitumkehrer","Deluminator","Denkarium"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Gegenstand zeigt Erinnerungen?",answers:["Denkarium","Erinnermich","Marauderkarte","Feuerkelch"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Gegenstand zeigt Personen in Hogwarts?",answers:["Marauderkarte","Denkarium","Erinnermich","Monsterbuch"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Gegenstand löscht und sammelt Licht?",answers:["Deluminator","Zeitumkehrer","Feuerkelch","Quaffel"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Gegenstand wird für Reisen per Kamin genutzt?",answers:["Flohpulver","Besenwachs","Bezoar","Einhornhaar"],correct:0},
  {category:"Objekte",difficulty:"schwer",question:"Welcher Gegenstand wählt Champions aus?",answers:["Feuerkelch","Sprechender Hut","Denkarium","Deluminator"],correct:0},
  {category:"Objekte",difficulty:"schwer",question:"Welcher Gegenstand hängt mit Nicolas Flamel zusammen?",answers:["Stein der Weisen","Auferstehungsstein","Elderstab","Zeitumkehrer"],correct:0},
  {category:"Objekte",difficulty:"schwer",question:"Welcher Gegenstand hängt mit Hermine im dritten Jahr zusammen?",answers:["Zeitumkehrer","Deluminator","Feuerkelch","Schnatz"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Gegenstand kann als Portschlüssel dienen?",answers:["Ein scheinbar gewöhnlicher Gegenstand","Nur ein Zauberstab","Nur ein Buch","Nur ein Besen"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Ball wird beim Quidditch durch Torringe geworfen?",answers:["Quaffel","Schnatz","Klatscher","Erinnermich"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Welche Bälle schlagen Spieler beim Quidditch weg?",answers:["Klatscher","Schnätze","Quaffeln","Erinnermiche"],correct:0},
  {category:"Objekte",difficulty:"schwer",question:"Welcher Gegenstand enthält Harrys ersten Hinweis im Trimagischen Turnier?",answers:["Goldenes Ei","Deluminator","Marauderkarte","Bezoar"],correct:0},
  {category:"Objekte",difficulty:"schwer",question:"Welches Objekt kann anzeigen, dass man etwas vergessen hat?",answers:["Erinnermich","Denkarium","Feuerkelch","Tarnumhang"],correct:0},
  {category:"Wesen",difficulty:"leicht",question:"Welches Wesen ist ein magischer Vogel, der wiedergeboren werden kann?",answers:["Phönix","Drache","Niffler","Kneazle"],correct:0},
  {category:"Wesen",difficulty:"leicht",question:"Welches Wesen sieht wie ein geflügeltes Pferd aus und ist skelettartig?",answers:["Thestral","Hippogreif","Zentaur","Kappa"],correct:0},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen ist halb Adler und halb Pferd?",answers:["Hippogreif","Thestral","Niffler","Dementor"],correct:0},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen ist halb Mensch und halb Pferd?",answers:["Zentaur","Hippogreif","Kobold","Hauself"],correct:0},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen ist für Gold und Verliese bekannt?",answers:["Kobold","Zentaur","Phönix","Kappa"],correct:0},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen kann in der Zaubererwelt als Diener leben?",answers:["Hauself","Dementor","Drache","Kappa"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen ist ein japanischer Wasserdämon?",answers:["Kappa","Niffler","Bowtruckle","Billywig"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen ist laut Wizarding World ein sehr gefährliches afrikanisches Tier?",answers:["Nundu","Mooncalf","Puffskein","Kneazle"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen kommt nur bei Vollmond aus seinem Bau?",answers:["Mooncalf","Niffler","Kappa","Phönix"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen ist klein, blau und kann Schweben auslösen?",answers:["Billywig","Bowtruckle","Puffskein","Kobold"],correct:0},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen liebt glänzende Dinge?",answers:["Niffler","Dementor","Basilisk","Thestral"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen ist ein baumbewohnender Pflanzenwächter?",answers:["Bowtruckle","Niffler","Kappa","Billywig"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen wirkt wie ein rundes, kuscheliges Haustier?",answers:["Puffskein","Nundu","Kappa","Basilisk"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen kann Feuer aus seinem Hinterteil schießen?",answers:["Feuerkrabbe","Billywig","Mooncalf","Niffler"],correct:0},
  {category:"Figuren",difficulty:"leicht",question:"Wer ist der Hauptgegner von Harry?",answers:["Lord Voldemort","Cornelius Fudge","Argus Filch","Gilderoy Lockhart"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Welcher Lehrer trägt im ersten Jahr einen Turban?",answers:["Quirinus Quirrell","Severus Snape","Filius Flitwick","Remus Lupin"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer ist im zweiten Jahr Lehrer für Verteidigung gegen die dunklen Künste?",answers:["Gilderoy Lockhart","Remus Lupin","Mad-Eye Moody","Dolores Umbridge"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer ist im dritten Jahr Lehrer für Verteidigung gegen die dunklen Künste?",answers:["Remus Lupin","Gilderoy Lockhart","Quirinus Quirrell","Horace Slughorn"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer wird im fünften Jahr Lehrerin für Verteidigung gegen die dunklen Künste?",answers:["Dolores Umbridge","Minerva McGonagall","Sybill Trelawney","Pomona Sprout"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Wer leitet das Zaubereiministerium im fünften Schuljahr?",answers:["Cornelius Fudge","Rufus Scrimgeour","Kingsley Shacklebolt","Arthur Weasley"],correct:0},
  {category:"Figuren",difficulty:"schwer",question:"Wer folgt später als Zaubereiminister auf Scrimgeour?",answers:["Pius Thicknesse","Barty Crouch","Ludo Bagman","Amos Diggory"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer ist ein berühmter Auror mit magischem Auge?",answers:["Alastor Moody","Kingsley Shacklebolt","Rufus Scrimgeour","Barty Crouch"],correct:0},
  {category:"Figuren",difficulty:"mittel",question:"Wer ist ein Mitglied des Ordens des Phönix und Auror?",answers:["Kingsley Shacklebolt","Ludo Bagman","Gilderoy Lockhart","Argus Filch"],correct:0},
  {category:"Hogwarts",difficulty:"leicht",question:"Welches Fach behandelt Zaubertränke?",answers:["Zaubertränke","Zauberkunst","Astronomie","Flugunterricht"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welches Fach behandelt Verteidigung gegen dunkle Magie?",answers:["Verteidigung gegen die dunklen Künste","Kräuterkunde","Geschichte der Zauberei","Wahrsagen"],correct:0},
  {category:"Hogwarts",difficulty:"mittel",question:"Welches Fach behandelt magische Pflanzen?",answers:["Kräuterkunde","Astronomie","Arithmantik","Zauberkunst"],correct:0},
  {category:"Hogwarts",difficulty:"schwer",question:"Welches Fach beschäftigt sich mit magischen Zahlen?",answers:["Arithmantik","Astronomie","Alte Runen","Wahrsagen"],correct:0},
  {category:"Hogwarts",difficulty:"schwer",question:"Welches Fach beschäftigt sich mit alten Schriftzeichen?",answers:["Alte Runen","Arithmantik","Verwandlung","Flugunterricht"],correct:0},
  {category:"Zaubersprüche",difficulty:"leicht",question:"Welcher Spruch wird häufig als Harrys Markenzeichen gesehen?",answers:["Expelliarmus","Alohomora","Nox","Incendio"],correct:0},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Spruch löscht einen Zauber oder beendet seine Wirkung?",answers:["Finite Incantatem","Lumos","Engorgio","Morsmordre"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauber erzeugt das Dunkle Mal?",answers:["Morsmordre","Sectumsempra","Riddikulus","Petrificus Totalus"],correct:0},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauber verursacht schnittartige Verletzungen?",answers:["Sectumsempra","Diffindo","Reducio","Aguamenti"],correct:0},
  {category:"Orte",difficulty:"leicht",question:"Wo liegt die magische Bank Gringotts?",answers:["Winkelgasse","Hogsmeade","Askaban","Godric's Hollow"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Wo befindet sich der Scherzartikelladen Weasleys Zauberhafte Zauberscherze?",answers:["Winkelgasse","Hogsmeade","Nocturngasse","Godric's Hollow"],correct:0},
  {category:"Orte",difficulty:"mittel",question:"Wo kauft man bei Madam Malkin ein?",answers:["Winkelgasse","Hogsmeade","Grimmauldplatz","Little Whinging"],correct:0},
  {category:"Objekte",difficulty:"leicht",question:"Was braucht man für Zaubertränke häufig als Gefäß?",answers:["Kessel","Besen","Schnatz","Denkarium"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Gegenstand dient vielen Zauberern zum Fliegen?",answers:["Besen","Denkarium","Erinnermich","Feuerkelch"],correct:0},
  {category:"Objekte",difficulty:"mittel",question:"Was ist ein Bezoar?",answers:["Ein Stein aus dem Magen einer Ziege","Ein Zauberstabkern","Ein Quidditch-Ball","Ein magisches Haustier"],correct:0},
  {category:"Wesen",difficulty:"leicht",question:"Welches Wesen ist Hagrids großer Halbbruder?",answers:["Grawp","Fang","Aragog","Firenze"],correct:0},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen ist der König der Schlangen in der Kammer?",answers:["Basilisk","Thestral","Kappa","Niffler"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen kann laut Legende tödlich durch seinen Blick sein?",answers:["Basilisk","Puffskein","Mooncalf","Bowtruckle"],correct:0},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen hat eine M.O.M.-Klassifikation von XXXXX?",answers:["Nundu","Puffskein","Mooncalf","Billywig"],correct:0}
];

const EXTRA_QUIZ_PACKS = [
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauberspruch passt zu: Geräusche überdecken?",answers:["Muffliato","Lumos","Accio","Diffindo"]},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauberspruch passt zu: eine Person zum Schweigen bringen?",answers:["Silencio","Reparo","Aguamenti","Engorgio"]},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauberspruch passt zu: kleinere Verletzungen heilen?",answers:["Episkey","Stupefy","Riddikulus","Nox"]},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauberspruch passt zu: Schienen und Verbände herbeizaubern?",answers:["Ferula","Expulso","Confundo","Accio"]},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauberspruch passt zu: eine betäubte Person wieder wecken?",answers:["Rennervate","Petrificus Totalus","Obliviate","Incendio"]},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauberspruch passt zu: einen Zaubereffekt beenden?",answers:["Finite","Wingardium Leviosa","Alohomora","Lumos"]},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauberspruch passt zu: eine Explosion auslösen?",answers:["Expulso","Nox","Reparo","Protego"]},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauberspruch passt zu: etwas sprengen oder bersten lassen?",answers:["Confringo","Aguamenti","Muffliato","Silencio"]},
  {category:"Zaubersprüche",difficulty:"leicht",question:"Welcher Zauberspruch passt zu: Feuer entzünden?",answers:["Incendio","Nox","Accio","Episkey"]},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauberspruch passt zu: Wasser abweisen?",answers:["Impervius","Engorgio","Diffindo","Confundo"]},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauberspruch passt zu: etwas vervielfältigen?",answers:["Geminio","Reducto","Finite","Rennervate"]},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauberspruch passt zu: in Gedanken eindringen?",answers:["Legilimens","Reparo","Alohomora","Tarantallegra"]},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauberspruch passt zu: den ganzen Körper versteifen?",answers:["Petrificus Totalus","Accio","Nox","Aguamenti"]},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauberspruch passt zu: unfreiwilliges Tanzen auslösen?",answers:["Tarantallegra","Lumos","Obliviate","Episkey"]},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauberspruch passt zu: Beine zusammenklammern?",answers:["Locomotor Mortis","Incendio","Protego","Geminio"]},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauberspruch passt zu: jemanden kopfüber anheben?",answers:["Levicorpus","Finite","Alohomora","Riddikulus"]},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauberspruch passt zu: Levicorpus rückgängig machen?",answers:["Liberacorpus","Silencio","Expulso","Reparo"]},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauberspruch passt zu: gefährliche Schnittwunden erzeugen?",answers:["Sectumsempra","Lumos","Confundo","Wingardium Leviosa"]},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauberspruch passt zu: feste Hindernisse zertrümmern?",answers:["Reducto","Nox","Episkey","Muffliato"]},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauberspruch passt zu: etwas vergrößern?",answers:["Engorgio","Reducio","Aguamenti","Finite"]},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauberspruch passt zu: etwas verkleinern?",answers:["Reducio","Engorgio","Stupefy","Diffindo"]},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauberspruch passt zu: etwas verschwinden lassen?",answers:["Evanesco","Accio","Protego","Riddikulus"]},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauberspruch passt zu: jemanden verwirren?",answers:["Confundo","Reparo","Lumos","Ferula"]},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauberspruch passt zu: Erinnerungen verändern?",answers:["Obliviate","Nox","Incendio","Tarantallegra"]},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauberspruch passt zu: Wasser erscheinen lassen?",answers:["Aguamenti","Confringo","Silencio","Rennervate"]},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauberspruch passt zu: Atemwege freimachen?",answers:["Anapneo","Expulso","Geminio","Levicorpus"]},
  {category:"Zaubersprüche",difficulty:"mittel",question:"Welcher Zauberspruch passt zu: etwas sauber trennen?",answers:["Diffindo","Lumos","Reparo","Protego"]},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauberspruch passt zu: etwas nach unten bewegen?",answers:["Descendo","Accio","Nox","Impervius"]},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauberspruch passt zu: Menschen in der Nähe aufspüren?",answers:["Homenum Revelio","Episkey","Alohomora","Incendio"]},
  {category:"Zaubersprüche",difficulty:"schwer",question:"Welcher Zauberspruch passt zu: einen Schutzbereich errichten?",answers:["Protego Totalum","Muffliato","Reducio","Obliviate"]},
  {category:"Figuren",difficulty:"leicht",question:"Welche Figur passt zu: Harrys Mutter?",answers:["Lily Potter","Petunia Dursley","Molly Weasley","Narzissa Malfoy"]},
  {category:"Figuren",difficulty:"leicht",question:"Welche Figur passt zu: Harrys Vater?",answers:["James Potter","Arthur Weasley","Lucius Malfoy","Xenophilius Lovegood"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: Harrys Pate?",answers:["Sirius Black","Remus Lupin","Severus Snape","Alastor Moody"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: ein Werwolf und Lehrer in Hogwarts?",answers:["Remus Lupin","Gilderoy Lockhart","Filius Flitwick","Horace Slughorn"]},
  {category:"Figuren",difficulty:"schwer",question:"Welche Figur passt zu: Animagus, Ratte und Verrat?",answers:["Peter Pettigrew","Barty Crouch Jr.","Igor Karkaroff","Stan Shunpike"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: strenge Verwandlungslehrerin?",answers:["Minerva McGonagall","Pomona Sprout","Sybill Trelawney","Aurora Sinistra"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: Zaubertränke, Halbblutprinz und Doppelleben?",answers:["Severus Snape","Quirinus Quirrell","Rufus Scrimgeour","Cornelius Fudge"]},
  {category:"Figuren",difficulty:"leicht",question:"Welche Figur passt zu: Schulleiter mit Phönix?",answers:["Albus Dumbledore","Argus Filch","Garrick Ollivander","Amos Diggory"]},
  {category:"Figuren",difficulty:"leicht",question:"Welche Figur passt zu: Wildhüter und Liebe zu großen Wesen?",answers:["Hagrid","Aberforth Dumbledore","Arthur Weasley","Lee Jordan"]},
  {category:"Figuren",difficulty:"leicht",question:"Welche Figur passt zu: freier Hauself mit Socke?",answers:["Dobby","Kreacher","Winky","Hokey"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: alter Hauself der Familie Black?",answers:["Kreacher","Dobby","Winky","Griphook"]},
  {category:"Figuren",difficulty:"schwer",question:"Welche Figur passt zu: Hauselfe mit Verbindung zu Barty Crouch?",answers:["Winky","Hokey","Kreacher","Dobby"]},
  {category:"Figuren",difficulty:"leicht",question:"Welche Figur passt zu: Ravenclaw, Klitterer und besondere Sicht auf die Welt?",answers:["Luna Lovegood","Cho Chang","Padma Patil","Lavender Brown"]},
  {category:"Figuren",difficulty:"leicht",question:"Welche Figur passt zu: Kröte Trevor und großer Mut?",answers:["Neville Longbottom","Dean Thomas","Seamus Finnigan","Colin Creevey"]},
  {category:"Figuren",difficulty:"leicht",question:"Welche Figur passt zu: Harrys Rivale aus Slytherin?",answers:["Draco Malfoy","Blaise Zabini","Vincent Crabbe","Gregory Goyle"]},
  {category:"Figuren",difficulty:"leicht",question:"Welche Figur passt zu: Rons Schwester und Quidditch-Talent?",answers:["Ginny Weasley","Fleur Delacour","Angelina Johnson","Katie Bell"]},
  {category:"Figuren",difficulty:"leicht",question:"Welche Figur passt zu: Weasley-Zwilling und Scherzartikel?",answers:["Fred Weasley","Percy Weasley","Charlie Weasley","Bill Weasley"]},
  {category:"Figuren",difficulty:"leicht",question:"Welche Figur passt zu: Weasley-Zwilling und Laden in der Winkelgasse?",answers:["George Weasley","Ron Weasley","Arthur Weasley","Molly Weasley"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: pflichtbewusster Weasley und Vertrauensschüler?",answers:["Percy Weasley","Charlie Weasley","Fred Weasley","Lee Jordan"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: Drachen in Rumänien?",answers:["Charlie Weasley","Bill Weasley","Percy Weasley","Ron Weasley"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: ältester Weasley und Gringotts?",answers:["Bill Weasley","Charlie Weasley","Arthur Weasley","Percy Weasley"]},
  {category:"Figuren",difficulty:"leicht",question:"Welche Figur passt zu: Mutter der Weasley-Kinder?",answers:["Molly Weasley","Narzissa Malfoy","Petunia Dursley","Augusta Longbottom"]},
  {category:"Figuren",difficulty:"leicht",question:"Welche Figur passt zu: Rons Vater und Muggel-Faszination?",answers:["Arthur Weasley","Amos Diggory","Vernon Dursley","Xenophilius Lovegood"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: Hufflepuff-Champion im Trimagischen Turnier?",answers:["Cedric Diggory","Viktor Krum","Roger Davies","Oliver Wood"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: bulgarischer Sucher und Durmstrang-Champion?",answers:["Viktor Krum","Cedric Diggory","Igor Karkaroff","Stan Shunpike"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: Beauxbatons-Champion?",answers:["Fleur Delacour","Cho Chang","Padma Patil","Parvati Patil"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: Ravenclaw-Sucherin und Harrys Schwarm?",answers:["Cho Chang","Luna Lovegood","Katie Bell","Angelina Johnson"]},
  {category:"Figuren",difficulty:"leicht",question:"Welche Figur passt zu: häufige Explosionen im Unterricht?",answers:["Seamus Finnigan","Dean Thomas","Colin Creevey","Cormac McLaggen"]},
  {category:"Figuren",difficulty:"leicht",question:"Welche Figur passt zu: Gryffindor-Schüler und guter Zeichner?",answers:["Dean Thomas","Seamus Finnigan","Lee Jordan","Oliver Wood"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: Mitglied von Dumbledores Armee und frühere Ron-Freundin?",answers:["Lavender Brown","Parvati Patil","Padma Patil","Katie Bell"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: Gryffindor-Schülerin und Ballpartnerin von Harry?",answers:["Parvati Patil","Padma Patil","Cho Chang","Susan Bones"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: Ravenclaw-Schülerin und Zwilling von Parvati?",answers:["Padma Patil","Parvati Patil","Lavender Brown","Hannah Abbott"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: Kapitän des Gryffindor-Quidditch-Teams?",answers:["Oliver Wood","Cormac McLaggen","Lee Jordan","Dean Thomas"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: Gryffindor-Jägerin und verfluchter Halskette?",answers:["Katie Bell","Angelina Johnson","Alicia Spinnet","Cho Chang"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: Gryffindor-Jägerin und spätere Frau von George?",answers:["Angelina Johnson","Katie Bell","Lavender Brown","Parvati Patil"]},
  {category:"Figuren",difficulty:"leicht",question:"Welche Figur passt zu: Quidditch-Kommentator aus Gryffindor?",answers:["Lee Jordan","Oliver Wood","Dean Thomas","Colin Creevey"]},
  {category:"Figuren",difficulty:"leicht",question:"Welche Figur passt zu: junger Fotograf und Harry-Fan?",answers:["Colin Creevey","Dennis Creevey","Justin Finch-Fletchley","Ernie Macmillan"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: Bruder von Albus und Wirt des Eberkopfs?",answers:["Aberforth Dumbledore","Elphias Doge","Dedalus Diggle","Mundungus Fletcher"]},
  {category:"Figuren",difficulty:"schwer",question:"Welche Figur passt zu: zwielichtiger Ordenskontakt und Dieb?",answers:["Mundungus Fletcher","Kingsley Shacklebolt","Rufus Scrimgeour","Dedalus Diggle"]},
  {category:"Figuren",difficulty:"mittel",question:"Welche Figur passt zu: Auror, Minister und tiefe Stimme?",answers:["Kingsley Shacklebolt","Alastor Moody","Cornelius Fudge","Barty Crouch Sr."]},
  {category:"Orte",difficulty:"leicht",question:"Welcher Ort passt zu: Schloss und Schule für junge Hexen und Zauberer?",answers:["Hogwarts","Askaban","Gringotts","Godric's Hollow"]},
  {category:"Orte",difficulty:"leicht",question:"Welcher Ort passt zu: lange Haustische und schwebende Kerzen?",answers:["Große Halle","Krankenflügel","Eulerei","Zaubertränke-Kerker"]},
  {category:"Orte",difficulty:"mittel",question:"Welcher Ort passt zu: Eingang hinter dem Porträt der Fetten Dame?",answers:["Gryffindor-Gemeinschaftsraum","Slytherin-Gemeinschaftsraum","Ravenclaw-Turm","Hufflepuff-Gemeinschaftsraum"]},
  {category:"Orte",difficulty:"mittel",question:"Welcher Ort passt zu: Tür mit Rätsel statt Passwort?",answers:["Ravenclaw-Turm","Gryffindor-Gemeinschaftsraum","Zaubertränke-Kerker","Eulerei"]},
  {category:"Orte",difficulty:"mittel",question:"Welcher Ort passt zu: Gemeinschaftsraum tief unten nahe dem See?",answers:["Slytherin-Gemeinschaftsraum","Ravenclaw-Turm","Große Halle","Astronomieturm"]},
  {category:"Orte",difficulty:"mittel",question:"Welcher Ort passt zu: Nähe zu Küche und Fässern?",answers:["Hufflepuff-Gemeinschaftsraum","Eulerei","Verbotener Wald","Raum der Wünsche"]},
  {category:"Orte",difficulty:"leicht",question:"Welcher Ort passt zu: Madam Pince und viele Bücher?",answers:["Bibliothek","Krankenflügel","Drei Besen","Ollivanders"]},
  {category:"Orte",difficulty:"leicht",question:"Welcher Ort passt zu: Madam Pomfrey und Genesung?",answers:["Krankenflügel","Große Halle","Eulerei","Zonko"]},
  {category:"Orte",difficulty:"mittel",question:"Welcher Ort passt zu: Unterricht bei Snape im Untergeschoss?",answers:["Zaubertränke-Kerker","Astronomieturm","Bibliothek","Quidditch-Feld"]},
  {category:"Orte",difficulty:"mittel",question:"Welcher Ort passt zu: Sternbeobachtung hoch über Hogwarts?",answers:["Astronomieturm","Krankenflügel","Hagrids Hütte","Honeydukes"]},
  {category:"Orte",difficulty:"leicht",question:"Welcher Ort passt zu: Schulpost und viele Eulen?",answers:["Eulerei","Drei Besen","Borgin und Burkes","Ministerium"]},
  {category:"Orte",difficulty:"mittel",question:"Welcher Ort passt zu: erscheint, wenn man ihn wirklich braucht?",answers:["Raum der Wünsche","Kammer des Schreckens","Nocturngasse","Askaban"]},
  {category:"Orte",difficulty:"mittel",question:"Welcher Ort passt zu: Basilisk und Parselmund?",answers:["Kammer des Schreckens","Große Halle","Godric's Hollow","Hogsmeade"]},
  {category:"Orte",difficulty:"leicht",question:"Welcher Ort passt zu: Grenze des Schulgeländes und gefährliche Begegnungen?",answers:["Verbotener Wald","Quidditch-Feld","Winkelgasse","King's Cross"]},
  {category:"Orte",difficulty:"leicht",question:"Welcher Ort passt zu: Hagrid wohnt dort?",answers:["Hagrids Hütte","Drei Besen","Shell Cottage","Grimmauldplatz 12"]},
  {category:"Orte",difficulty:"leicht",question:"Welcher Ort passt zu: Torringe, Besen und Hausmannschaften?",answers:["Quidditch-Feld","Bibliothek","Eulerei","Krankenflügel"]},
  {category:"Orte",difficulty:"leicht",question:"Welcher Ort passt zu: magische Einkaufsstraße in London?",answers:["Winkelgasse","Nocturngasse","Spinner's End","Ligusterweg"]},
  {category:"Orte",difficulty:"leicht",question:"Welcher Ort passt zu: Bank der Zaubererwelt?",answers:["Gringotts","Ollivanders","Honeydukes","Zonko"]},
  {category:"Orte",difficulty:"leicht",question:"Welcher Ort passt zu: Zauberstäbe suchen ihre Besitzer?",answers:["Ollivanders","Madam Malkins","Eeylops","Flourish and Blotts"]},
  {category:"Orte",difficulty:"mittel",question:"Welcher Ort passt zu: Schulbücher und magische Bücher?",answers:["Flourish and Blotts","Honeydukes","Drei Besen","Eberkopf"]},
  {category:"Orte",difficulty:"mittel",question:"Welcher Ort passt zu: Umhänge für alle Gelegenheiten?",answers:["Madam Malkins","Gringotts","Ollivanders","Zonko"]},
  {category:"Orte",difficulty:"mittel",question:"Welcher Ort passt zu: Harry kauft dort Hedwig?",answers:["Eeylops Eulenkaufhaus","Borgin und Burkes","Honeydukes","Drei Besen"]},
  {category:"Orte",difficulty:"leicht",question:"Welcher Ort passt zu: Pub zwischen Muggelwelt und Winkelgasse?",answers:["Tropfender Kessel","Drei Besen","Eberkopf","Fuchsbau"]},
  {category:"Orte",difficulty:"leicht",question:"Welcher Ort passt zu: einziges Zaubererdorf Großbritanniens?",answers:["Hogsmeade","Godric's Hollow","Little Hangleton","Ottery St Catchpole"]},
  {category:"Orte",difficulty:"leicht",question:"Welcher Ort passt zu: Butterbier und Madam Rosmerta?",answers:["Drei Besen","Eberkopf","Tropfender Kessel","Honeydukes"]},
  {category:"Orte",difficulty:"mittel",question:"Welcher Ort passt zu: Aberforths Pub in Hogsmeade?",answers:["Eberkopf","Drei Besen","Zonko","Tropfender Kessel"]},
  {category:"Orte",difficulty:"leicht",question:"Welcher Ort passt zu: Süßigkeiten in Hogsmeade?",answers:["Honeydukes","Ollivanders","Gringotts","Madam Malkins"]},
  {category:"Orte",difficulty:"mittel",question:"Welcher Ort passt zu: Scherzartikel in Hogsmeade?",answers:["Zonko","Honeydukes","Drei Besen","Eeylops"]},
  {category:"Orte",difficulty:"leicht",question:"Welcher Ort passt zu: Zauberergefängnis und Dementoren?",answers:["Askaban","Nurmengard","Gringotts","Ministerium"]},
  {category:"Orte",difficulty:"mittel",question:"Welcher Ort passt zu: Regierungszentrale der Zaubererwelt?",answers:["Ministerium für Zauberei","Hogwarts","Winkelgasse","Godric's Hollow"]},
  {category:"Objekte",difficulty:"leicht",question:"Welcher Gegenstand passt zu: macht den Träger unsichtbar?",answers:["Tarnumhang","Denkarium","Erinnermich","Feuerkelch"]},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Gegenstand passt zu: Elixier des Lebens und Alchemie?",answers:["Stein der Weisen","Auferstehungsstein","Mondstein","Bezoar"]},
  {category:"Objekte",difficulty:"leicht",question:"Welcher Gegenstand passt zu: wählt Champions aus?",answers:["Feuerkelch","Sprechender Hut","Deluminator","Quaffel"]},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Gegenstand passt zu: Erinnerungen betrachten?",answers:["Denkarium","Zeitumkehrer","Erinnermich","Heuler"]},
  {category:"Objekte",difficulty:"leicht",question:"Welcher Gegenstand passt zu: teilt Schüler in Häuser ein?",answers:["Sprechender Hut","Feuerkelch","Tarnumhang","Zauberstab"]},
  {category:"Objekte",difficulty:"leicht",question:"Welcher Gegenstand passt zu: zeigt Personen und Wege in Hogwarts?",answers:["Marauderkarte","Tagesprophet","Klitterer","Quaffel"]},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Gegenstand passt zu: Hermine schafft mehrere Unterrichtsstunden?",answers:["Zeitumkehrer","Deluminator","Elderstab","Erinnermich"]},
  {category:"Objekte",difficulty:"schwer",question:"Welcher Gegenstand passt zu: Dumbledore kann Licht auslöschen und zurückholen?",answers:["Deluminator","Denkarium","Sprechender Hut","Feuerkelch"]},
  {category:"Objekte",difficulty:"schwer",question:"Welcher Gegenstand passt zu: mächtigster der drei Heiligtümer?",answers:["Elderstab","Auferstehungsstein","Tarnumhang","Bezoar"]},
  {category:"Objekte",difficulty:"schwer",question:"Welcher Gegenstand passt zu: mit Verstorbenen in Verbindung bringen?",answers:["Auferstehungsstein","Stein der Weisen","Zeitumkehrer","Deluminator"]},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Gegenstand passt zu: enthält einen Teil von Voldemorts Seele?",answers:["Horkrux","Heuler","Quaffel","Erinnermich"]},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Gegenstand passt zu: Tom Riddle schreibt zurück?",answers:["Tagebuch","Klitterer","Marauderkarte","Monsterbuch"]},
  {category:"Objekte",difficulty:"schwer",question:"Welcher Gegenstand passt zu: Erbstück der Familie Gaunt?",answers:["Gaunts Ring","Ravenclaws Diadem","Hufflepuffs Becher","Gryffindors Schwert"]},
  {category:"Objekte",difficulty:"schwer",question:"Welcher Gegenstand passt zu: Slytherins Symbol als Horkrux?",answers:["Slytherins Medaillon","Gaunts Ring","Tarnumhang","Deluminator"]},
  {category:"Objekte",difficulty:"schwer",question:"Welcher Gegenstand passt zu: Hufflepuffs Erbstück?",answers:["Hufflepuffs Becher","Ravenclaws Diadem","Slytherins Medaillon","Gaunts Ring"]},
  {category:"Objekte",difficulty:"schwer",question:"Welcher Gegenstand passt zu: verlorenes Erbstück von Ravenclaw?",answers:["Ravenclaws Diadem","Hufflepuffs Becher","Elderstab","Feuerkelch"]},
  {category:"Objekte",difficulty:"schwer",question:"Welcher Gegenstand passt zu: Waffe, die sich würdigen Gryffindors zeigt?",answers:["Gryffindors Schwert","Elderstab","Feuerblitz","Zauberstab von Draco"]},
  {category:"Objekte",difficulty:"leicht",question:"Welcher Gegenstand passt zu: kleinster Ball beim Quidditch?",answers:["Goldener Schnatz","Quaffel","Klatscher","Portschlüssel"]},
  {category:"Objekte",difficulty:"leicht",question:"Welcher Gegenstand passt zu: Ball, mit dem Jäger Tore werfen?",answers:["Quaffel","Goldener Schnatz","Klatscher","Erinnermich"]},
  {category:"Objekte",difficulty:"leicht",question:"Welcher Gegenstand passt zu: gefährlicher Ball, den Treiber abwehren?",answers:["Klatscher","Quaffel","Schnatz","Heuler"]},
  {category:"Objekte",difficulty:"leicht",question:"Welcher Gegenstand passt zu: Harrys erster eigener Rennbesen?",answers:["Nimbus 2000","Feuerblitz","Sauberwisch 7","Silberpfeil"]},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Gegenstand passt zu: Harrys besonders schneller Besen ab dem dritten Jahr?",answers:["Feuerblitz","Nimbus 2000","Sternschnuppe","Sauberwisch 11"]},
  {category:"Objekte",difficulty:"leicht",question:"Welcher Gegenstand passt zu: Reisen durch Kamine?",answers:["Flohpulver","Portschlüssel","Denkarium","Zeitumkehrer"]},
  {category:"Objekte",difficulty:"leicht",question:"Welcher Gegenstand passt zu: unscheinbares Ding als Reisemittel?",answers:["Portschlüssel","Feuerkelch","Erinnermich","Quaffel"]},
  {category:"Objekte",difficulty:"leicht",question:"Welcher Gegenstand passt zu: erinnert daran, dass etwas vergessen wurde?",answers:["Erinnermich","Heuler","Deluminator","Bezoar"]},
  {category:"Objekte",difficulty:"leicht",question:"Welcher Gegenstand passt zu: Brief, der lautstark schimpft?",answers:["Heuler","Tagesprophet","Klitterer","Marauderkarte"]},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Gegenstand passt zu: Weasleys Scherzartikel zum heimlichen Zuhören?",answers:["Langziehohren","Erinnermich","Deluminator","Feuerkelch"]},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Gegenstand passt zu: wirkt gegen viele Gifte?",answers:["Bezoar","Mondstein","Drachenblut","Flohpulver"]},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Trank passt zu: Aussehen einer anderen Person annehmen?",answers:["Vielsaft-Trank","Felix Felicis","Amortentia","Veritaserum"]},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Trank passt zu: flüssiges Glück?",answers:["Felix Felicis","Vielsaft-Trank","Amortentia","Schrumpflösung"]},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Trank passt zu: starker Liebestrank?",answers:["Amortentia","Felix Felicis","Veritaserum","Wolfsbann-Trank"]},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Trank passt zu: zwingt zur Wahrheit?",answers:["Veritaserum","Felix Felicis","Amortentia","Schlaftrunk"]},
  {category:"Objekte",difficulty:"mittel",question:"Welcher Gegenstand passt zu: Schulbuch, das zubeißen kann?",answers:["Monsterbuch der Monster","Tagebuch","Denkarium","Klitterer"]},
  {category:"Objekte",difficulty:"leicht",question:"Welcher Gegenstand passt zu: magisches Werkzeug mit Kern und Holz?",answers:["Zauberstab","Quaffel","Bezoar","Schnatz"]},
  {category:"Objekte",difficulty:"leicht",question:"Welcher Gegenstand passt zu: bringt Schüler mit Dampflok nach Hogwarts?",answers:["Fahrkarte für den Hogwarts-Express","Flohpulver","Portschlüssel","Marauderkarte"]},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen passt zu: nur sichtbar nach einer Begegnung mit dem Tod?",answers:["Thestral","Hippogreif","Niffler","Bowtruckle"]},
  {category:"Wesen",difficulty:"leicht",question:"Welches Wesen passt zu: Mischung aus Adler und Pferd?",answers:["Hippogreif","Zentaur","Phönix","Basilisk"]},
  {category:"Wesen",difficulty:"leicht",question:"Welches Wesen passt zu: kann aus Asche neu entstehen?",answers:["Phönix","Drache","Einhorn","Kobold"]},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen passt zu: sein Blick kann tödlich sein?",answers:["Basilisk","Troll","Flubberwurm","Niffler"]},
  {category:"Wesen",difficulty:"leicht",question:"Welches Wesen passt zu: saugt Freude aus Menschen?",answers:["Dementor","Hauself","Einhorn","Bowtruckle"]},
  {category:"Wesen",difficulty:"leicht",question:"Welches Wesen passt zu: groß, schuppig und feuerspeiend?",answers:["Drache","Zentaur","Kappa","Grindeloh"]},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen passt zu: gefährliche Drachenart im Trimagischen Turnier?",answers:["Ungarischer Hornschwanz","Norwegischer Stachelbuckel","Walisischer Grünling","Chinesischer Feuerball"]},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen passt zu: Hagrids Drache Norbert?",answers:["Norwegischer Stachelbuckel","Ungarischer Hornschwanz","Hebridischer Schwarzdrache","Peruanischer Vipernzahn"]},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen passt zu: Aragog gehört zu dieser Art?",answers:["Acromantula","Basilisk","Nundu","Kappa"]},
  {category:"Wesen",difficulty:"leicht",question:"Welches Wesen passt zu: halb Mensch, halb Pferd?",answers:["Zentaur","Hippogreif","Thestral","Kelpie"]},
  {category:"Wesen",difficulty:"leicht",question:"Welches Wesen passt zu: reines, silberweißes Tier mit heilkräftigem Haar?",answers:["Einhorn","Niffler","Grindeloh","Troll"]},
  {category:"Wesen",difficulty:"leicht",question:"Welches Wesen passt zu: Gringotts und Verliese?",answers:["Kobold","Hauself","Dementor","Bowtruckle"]},
  {category:"Wesen",difficulty:"leicht",question:"Welches Wesen passt zu: Dobby ist eines davon?",answers:["Hauself","Kobold","Zentaur","Irrwicht"]},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen passt zu: liebt Glitzerndes und Schätze?",answers:["Niffler","Flubberwurm","Basilisk","Veela"]},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen passt zu: bewacht Bäume, aus denen Zauberstäbe entstehen können?",answers:["Bowtruckle","Kappa","Doxy","Troll"]},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen passt zu: Wasserwesen, das Menschen packen kann?",answers:["Grindeloh","Phönix","Einhorn","Dementor"]},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen passt zu: gestaltwandelndes Wasserwesen aus schottischen Legenden?",answers:["Kelpie","Niffler","Diricawl","Acromantula"]},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen passt zu: japanisches Wasserwesen mit Mulde auf dem Kopf?",answers:["Kappa","Grindeloh","Bowtruckle","Flubberwurm"]},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen passt zu: Remus Lupin bei Vollmond?",answers:["Werwolf","Vampir","Inferius","Irrwicht"]},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen passt zu: Grawp gehört dazu?",answers:["Riese","Troll","Zentaur","Kobold"]},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen passt zu: verführerische Magie und Fleur Delacours Abstammung?",answers:["Veela","Dementor","Thestral","Niffler"]},
  {category:"Wesen",difficulty:"mittel",question:"Welches Wesen passt zu: nimmt die Form der größten Angst an?",answers:["Irrwicht","Inferius","Kappa","Phönix"]},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen passt zu: von dunkler Magie bewegter Leichnam?",answers:["Inferius","Dementor","Werwolf","Flubberwurm"]},
  {category:"Wesen",difficulty:"leicht",question:"Welches Wesen passt zu: große Keule und gefährliche Toilettenbegegnung?",answers:["Troll","Riese","Kobold","Niffler"]},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen passt zu: Hagrids gezüchtete knallende Unterrichts-Kreatur?",answers:["Knallrümpfiger Kröter","Flubberwurm","Bowtruckle","Diricawl"]},
  {category:"Wesen",difficulty:"leicht",question:"Welches Wesen passt zu: wurmartig und sehr unspektakulär im Unterricht?",answers:["Flubberwurm","Nundu","Basilisk","Thestral"]},
  {category:"Wesen",difficulty:"schwer",question:"Welches Wesen passt zu: kann verschwinden und Muggel kennen es als Dodo?",answers:["Diricawl","Kappa","Kelpie","Mooncalf"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Wer gründete Gryffindor?",answers:["Godric Gryffindor","Helga Hufflepuff","Rowena Ravenclaw","Salazar Slytherin"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Wer gründete Hufflepuff?",answers:["Helga Hufflepuff","Godric Gryffindor","Rowena Ravenclaw","Salazar Slytherin"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Wer gründete Ravenclaw?",answers:["Rowena Ravenclaw","Helga Hufflepuff","Godric Gryffindor","Salazar Slytherin"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Wer gründete Slytherin?",answers:["Salazar Slytherin","Godric Gryffindor","Helga Hufflepuff","Rowena Ravenclaw"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Welches Haus steht besonders für Mut?",answers:["Gryffindor","Ravenclaw","Hufflepuff","Slytherin"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Welches Haus steht besonders für Klugheit?",answers:["Ravenclaw","Gryffindor","Hufflepuff","Slytherin"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Welches Haus steht besonders für Loyalität?",answers:["Hufflepuff","Ravenclaw","Slytherin","Gryffindor"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Welches Haus steht besonders für Ehrgeiz?",answers:["Slytherin","Hufflepuff","Gryffindor","Ravenclaw"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Welches Fach unterrichtet Minerva McGonagall?",answers:["Verwandlung","Zauberkunst","Kräuterkunde","Wahrsagen"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Welches Fach unterrichtet Filius Flitwick?",answers:["Zauberkunst","Zaubertränke","Astronomie","Geschichte der Zauberei"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Welches Fach unterrichtet Pomona Sprout?",answers:["Kräuterkunde","Alte Runen","Verwandlung","Wahrsagen"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Welches Fach unterrichtet Severus Snape am Anfang?",answers:["Zaubertränke","Zauberkunst","Astronomie","Muggelkunde"]},
  {category:"Hogwarts",difficulty:"mittel",question:"Welches Fach unterrichtet Professor Binns?",answers:["Geschichte der Zauberei","Verwandlung","Kräuterkunde","Verteidigung"]},
  {category:"Hogwarts",difficulty:"mittel",question:"Welches Fach unterrichtet Professor Sinistra?",answers:["Astronomie","Arithmantik","Zauberkunst","Pflege magischer Geschöpfe"]},
  {category:"Hogwarts",difficulty:"mittel",question:"Wer ist für Flugunterricht bekannt?",answers:["Madam Hooch","Madam Pince","Madam Pomfrey","Madam Malkin"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Welches Fach unterrichtet Sybill Trelawney?",answers:["Wahrsagen","Zaubertränke","Verwandlung","Zauberkunst"]},
  {category:"Hogwarts",difficulty:"mittel",question:"Welche Figur übernimmt zeitweise Wahrsagen in Hogwarts?",answers:["Firenze","Bane","Ronan","Magorian"]},
  {category:"Hogwarts",difficulty:"mittel",question:"Welcher Lehrer kehrt später als Zaubertranklehrer zurück?",answers:["Horace Slughorn","Gilderoy Lockhart","Remus Lupin","Quirinus Quirrell"]},
  {category:"Hogwarts",difficulty:"mittel",question:"Wer unterrichtet im dritten Jahr Verteidigung gegen die dunklen Künste?",answers:["Remus Lupin","Gilderoy Lockhart","Dolores Umbridge","Quirinus Quirrell"]},
  {category:"Hogwarts",difficulty:"mittel",question:"Wer unterrichtet im zweiten Jahr Verteidigung gegen die dunklen Künste?",answers:["Gilderoy Lockhart","Remus Lupin","Severus Snape","Alastor Moody"]},
  {category:"Hogwarts",difficulty:"mittel",question:"Wer unterrichtet im fünften Jahr Verteidigung gegen die dunklen Künste?",answers:["Dolores Umbridge","Remus Lupin","Horace Slughorn","Firenze"]},
  {category:"Hogwarts",difficulty:"schwer",question:"Wer steckt im vierten Jahr hinter dem Unterricht von Professor Moody?",answers:["Barty Crouch Jr.","Peter Pettigrew","Lucius Malfoy","Igor Karkaroff"]},
  {category:"Hogwarts",difficulty:"mittel",question:"Welcher Geist gehört zu Hufflepuff?",answers:["Der Fette Mönch","Die Graue Dame","Der Blutige Baron","Der Fast Kopflose Nick"]},
  {category:"Hogwarts",difficulty:"mittel",question:"Welcher Geist gehört zu Ravenclaw?",answers:["Die Graue Dame","Der Fette Mönch","Der Blutige Baron","Peeves"]},
  {category:"Hogwarts",difficulty:"mittel",question:"Welcher Geist gehört zu Slytherin?",answers:["Der Blutige Baron","Der Fast Kopflose Nick","Die Graue Dame","Der Fette Mönch"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Welcher Geist gehört zu Gryffindor?",answers:["Der Fast Kopflose Nick","Peeves","Der Fette Mönch","Der Blutige Baron"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Wer ist der Poltergeist von Hogwarts?",answers:["Peeves","Binns","Firenze","Flitwick"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Wer ist Hausmeister von Hogwarts?",answers:["Argus Filch","Rubeus Hagrid","Filius Flitwick","Cuthbert Binns"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Wie heißt Filchs Katze?",answers:["Mrs Norris","Krummbein","Hedwig","Arnold"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Wer leitet die Bibliothek?",answers:["Madam Pince","Madam Pomfrey","Madam Hooch","Madam Rosmerta"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Wer arbeitet im Krankenflügel?",answers:["Madam Pomfrey","Madam Pince","Madam Hooch","Professor Vector"]},
  {category:"Hogwarts",difficulty:"mittel",question:"In welchem Schuljahr stehen die ZAG-Prüfungen an?",answers:["Fünftes Schuljahr","Drittes Schuljahr","Erstes Schuljahr","Siebtes Schuljahr"]},
  {category:"Hogwarts",difficulty:"mittel",question:"Welche Prüfungen sind die höheren Abschlussprüfungen in Hogwarts?",answers:["UTZ","ZAG","MUG","OWL junior"]},
  {category:"Hogwarts",difficulty:"leicht",question:"Wofür sammeln die Häuser in Hogwarts Punkte?",answers:["Hauspokal","Feuerkelch","Quidditch-WM","Trimagisches Turnier"]},
  {category:"Hogwarts",difficulty:"mittel",question:"Welche Schülerrolle hilft Lehrern und sorgt für Ordnung?",answers:["Vertrauensschüler","Sucher","Treiber","Auror"]}
];

window.QUIZ_QUESTIONS.push(...EXTRA_QUIZ_PACKS.map((item) => ({...item, correct: 0})));

window.MYSTERY_ITEMS = [
  {name:"Hedwig",category:"Figuren",hints:["Dieses Tier ist meist weiß.","Es bringt Nachrichten.","Es gehört Harry."]},
  {name:"Ron Weasley",category:"Figuren",hints:["Diese Figur kommt aus einer großen Familie.","Sie hat rote Haare.","Sie ist Harrys bester Freund."]},
  {name:"Hermine Granger",category:"Figuren",hints:["Diese Figur lernt sehr viel.","Sie ist in Gryffindor.","Sie ist mit Harry und Ron befreundet."]},
  {name:"Albus Dumbledore",category:"Figuren",hints:["Diese Figur trägt viel Verantwortung in Hogwarts.","Sie besitzt einen Phönix.","Sie ist Schulleiter von Hogwarts."]},
  {name:"Severus Snape",category:"Figuren",hints:["Diese Figur wirkt streng und geheimnisvoll.","Sie unterrichtet Zaubertränke.","Sie ist der Halbblutprinz."]},
  {name:"Hagrid",category:"Figuren",hints:["Diese Figur liebt magische Wesen.","Sie ist außergewöhnlich groß.","Sie ist Wildhüter von Hogwarts."]},
  {name:"Sirius Black",category:"Figuren",hints:["Diese Figur kann sich verwandeln.","Sie war in Askaban.","Sie ist Harrys Pate."]},
  {name:"Dobby",category:"Figuren",hints:["Diese Figur arbeitet für eine Zaubererfamilie.","Sie will Harry warnen.","Sie ist ein Hauself."]},
  {name:"Winkelgasse",category:"Orte",hints:["An diesem Ort gibt es viele magische Läden.","Man erreicht ihn über einen Pub.","Schüler kaufen hier Schulbedarf."]},
  {name:"Hogsmeade",category:"Orte",hints:["Dieser Ort ist ein Dorf.","Schüler besuchen ihn ab dem dritten Jahr.","Hier gibt es die Drei Besen."]},
  {name:"Gringotts",category:"Orte",hints:["Dieser Ort wird von Kobolden betrieben.","Er hat tiefe Verliese.","Es ist die Bank der Zaubererwelt."]},
  {name:"Fuchsbau",category:"Orte",hints:["Dieser Ort ist ein sehr lebendiges Zuhause.","Viele Weasleys wohnen hier.","Das Gebäude steht etwas schief."]},
  {name:"Verbotener Wald",category:"Orte",hints:["Dieser Ort liegt bei Hogwarts.","Dort leben gefährliche Wesen.","Schüler sollen ihn meiden."]},
  {name:"Tarnumhang",category:"Objekte",hints:["Dieser Gegenstand ist sehr selten.","Er hilft beim Schleichen.","Er macht unsichtbar."]},
  {name:"Feuerkelch",category:"Objekte",hints:["Dieser Gegenstand wählt Namen aus.","Er spielt bei einem Turnier eine Rolle.","Er bestimmt die Champions."]},
  {name:"Marauderkarte",category:"Objekte",hints:["Dieser Gegenstand sieht wie Pergament aus.","Er zeigt Wege und Personen.","Er gehört zu den Rumtreibern."]},
  {name:"Zeitumkehrer",category:"Objekte",hints:["Dieser Gegenstand ist klein und tragbar.","Hermine nutzt ihn für den Unterricht.","Er verändert die Zeit."]},
  {name:"Denkarium",category:"Objekte",hints:["Dieser Gegenstand wirkt wie eine Schale.","Man kann darin etwas betrachten.","Er zeigt Erinnerungen."]},
  {name:"Lumos",category:"Zaubersprüche",hints:["Dieser Zauberspruch ist kurz.","Er hilft im Dunkeln.","Er erzeugt Licht."]},
  {name:"Alohomora",category:"Zaubersprüche",hints:["Dieser Zauberspruch löst ein Hindernis.","Hermine nutzt ihn früh.","Er öffnet Schlösser."]},
  {name:"Accio",category:"Zaubersprüche",hints:["Dieser Zauberspruch bewegt etwas zu dir.","Er ist im Alltag sehr nützlich.","Er ruft Gegenstände herbei."]},
  {name:"Expelliarmus",category:"Zaubersprüche",hints:["Dieser Zauberspruch ist Harrys Spezialität.","Er beendet viele Duelle.","Er entwaffnet Gegner."]},
  {name:"Expecto Patronum",category:"Zaubersprüche",hints:["Dieser Zauberspruch braucht starke gute Gedanken.","Er hat eine persönliche Form.","Er schützt vor Dementoren."]},
  {name:"Thestral",category:"Wesen",hints:["Dieses Wesen ist nicht für jeden sichtbar.","Es zieht Kutschen.","Man sieht es erst nach einer bestimmten Erfahrung."]},
  {name:"Seidenschnabel",category:"Wesen",hints:["Dieses Wesen ist sehr stolz.","Man sollte sich vor ihm verbeugen.","Es ist ein Hippogreif."]},
  {name:"Fawkes",category:"Wesen",hints:["Dieses Wesen gehört zu Dumbledore.","Es kann neu geboren werden.","Es ist ein Phönix."]},
  {name:"Aragog",category:"Wesen",hints:["Dieses Wesen lebt im Wald.","Es hat viele Nachkommen.","Es ist eine riesige Spinne."]},
  {name:"Dementor",category:"Wesen",hints:["Dieses Wesen wirkt kalt und furchteinflößend.","Es bewacht Askaban.","Es saugt Freude aus Menschen."]},
  {name:"Sprechender Hut",category:"Objekte",hints:["Dieser Gegenstand ist sehr alt.","Er prüft neue Schüler.","Er teilt die Hogwarts-Häuser zu."]},
  {name:"Ollivanders",category:"Orte",hints:["Dieser Ort ist ein Laden.","Hier passt etwas Magisches zu dir.","Hier kauft man Zauberstäbe."]},
  {name:"Luna Lovegood",category:"Figuren",hints:["Diese Figur sieht die Welt anders.","Sie ist in Ravenclaw.","Ihr Vater macht den Klitterer."]},
  {name:"Neville Longbottom",category:"Figuren",hints:["Diese Figur wirkt am Anfang unsicher.","Sie besitzt eine Kröte.","Sie wird sehr mutig."]},
  {name:"Draco Malfoy",category:"Figuren",hints:["Diese Figur kommt aus einer reichen Familie.","Sie ist in Slytherin.","Sie ist oft Harrys Gegner."]},
  {name:"Ginny Weasley",category:"Figuren",hints:["Diese Figur ist die jüngste in ihrer Familie.","Sie spielt Quidditch.","Sie ist Rons Schwester."]},
  {name:"Ligusterweg 4",category:"Orte",hints:["Diese Adresse ist nicht magisch.","Harry wächst hier auf.","Hier wohnen die Dursleys."]},
  {name:"Askaban",category:"Orte",hints:["Dieser Ort ist sehr gefürchtet.","Dementoren bewachen ihn.","Es ist ein Zauberergefängnis."]},
  {name:"Raum der Wünsche",category:"Orte",hints:["Dieser Ort erscheint nicht immer.","Er passt sich dem Bedarf an.","Man findet ihn in Hogwarts."]},
  {name:"King's Cross",category:"Orte",hints:["Dieser Ort liegt in London.","Viele Muggel kennen ihn.","Von hier fährt der Hogwarts-Express."]},
  {name:"Goldener Schnatz",category:"Objekte",hints:["Dieser Gegenstand ist klein.","Er ist sehr schnell.","Sucher wollen ihn fangen."]},
  {name:"Nimbus 2000",category:"Objekte",hints:["Dieser Gegenstand ist ein Sportgerät.","Harry bekommt ihn früh.","Es ist ein Besen."]},
  {name:"Erinnermich",category:"Objekte",hints:["Dieser Gegenstand ist rund.","Neville besitzt so etwas.","Er zeigt, dass man etwas vergessen hat."]},
  {name:"Tom Riddles Tagebuch",category:"Objekte",hints:["Dieser Gegenstand sieht harmlos aus.","Er schreibt zurück.","Er ist ein Horkrux."]},
  {name:"Incendio",category:"Zaubersprüche",hints:["Dieser Zauberspruch ist nützlich für Flammen.","Er ist kurz und direkt.","Er erzeugt Feuer."]},
  {name:"Petrificus Totalus",category:"Zaubersprüche",hints:["Dieser Zauberspruch macht bewegungsunfähig.","Hermine nutzt ihn gegen Neville.","Er ist der Ganzkörperklammer-Zauber."]},
  {name:"Riddikulus",category:"Zaubersprüche",hints:["Dieser Zauberspruch braucht Humor.","Er wirkt gegen Irrwichte.","Er macht etwas Furchtbares lächerlich."]},
  {name:"Fluffy",category:"Wesen",hints:["Dieses Wesen bewacht etwas.","Es mag Musik.","Es hat drei Köpfe."]},
  {name:"Norbert",category:"Wesen",hints:["Dieses Wesen ist als Haustier gefährlich.","Hagrid zieht es kurz auf.","Es ist ein Drache."]},
  {name:"Basilisk",category:"Wesen",hints:["Dieses Wesen ist sehr alt und gefährlich.","Sein Blick kann töten.","Es lebt in der Kammer des Schreckens."]},
  {name:"Kobold",category:"Wesen",hints:["Dieses Wesen ist klein und klug.","Es arbeitet mit Gold und Verliesen.","Viele davon arbeiten in Gringotts."]},
  {name:"Hauself",category:"Wesen",hints:["Dieses Wesen dient Zaubererfamilien.","Kleidung kann Freiheit bedeuten.","Dobby ist eines dieser Wesen."]},
  {name:"Arthur Weasley",category:"Figuren",hints:["Diese Figur arbeitet im Ministerium.","Sie interessiert sich sehr für Muggel.","Sie ist Rons Vater."]},
  {name:"Molly Weasley",category:"Figuren",hints:["Diese Figur sorgt sich stark um ihre Familie.","Sie lebt im Fuchsbau.","Sie ist Rons Mutter."]},
  {name:"Nymphadora Tonks",category:"Figuren",hints:["Diese Figur kann ihr Aussehen verändern.","Sie ist Aurorin.","Sie mag ihren Vornamen nicht besonders."]},
  {name:"Lucius Malfoy",category:"Figuren",hints:["Diese Figur hat großen Einfluss.","Sie ist Dracos Vater.","Sie trägt oft einen Gehstock mit Zauberstab."]},
  {name:"Rita Kimmkorn",category:"Figuren",hints:["Diese Figur schreibt Artikel.","Sie sucht gerne Skandale.","Sie ist eine Reporterin."]},
  {name:"Große Halle",category:"Orte",hints:["Dieser Ort liegt in Hogwarts.","Hier gibt es lange Haustische.","Hier essen die Schüler gemeinsam."]},
  {name:"Krankenflügel",category:"Orte",hints:["Dieser Ort liegt in Hogwarts.","Madam Pomfrey arbeitet dort.","Verletzte Schüler werden hier versorgt."]},
  {name:"Eberkopf",category:"Orte",hints:["Dieser Ort ist ein Pub.","Er liegt in Hogsmeade.","Aberforth betreibt ihn."]},
  {name:"Godric's Hollow",category:"Orte",hints:["Dieser Ort ist ein Dorf.","Harrys Eltern lebten dort.","Dort liegt ihr Grab."]},
  {name:"Nocturngasse",category:"Orte",hints:["Diese Gasse ist düster.","Sie ist mit der Winkelgasse verbunden.","Dort gibt es dunkle Läden."]},
  {name:"Monsterbuch der Monster",category:"Objekte",hints:["Dieser Gegenstand ist ein Schulbuch.","Es kann nach Lesern schnappen.","Hagrid nutzt es für Unterricht."]},
  {name:"Elderstab",category:"Objekte",hints:["Dieser Gegenstand ist sehr mächtig.","Er gehört zu den Heiligtümern des Todes.","Er ist ein besonderer Zauberstab."]},
  {name:"Auferstehungsstein",category:"Objekte",hints:["Dieser Gegenstand ist klein.","Er gehört zu den Heiligtümern des Todes.","Er steht mit Verstorbenen in Verbindung."]},
  {name:"Portschlüssel",category:"Objekte",hints:["Dieser Gegenstand kann unscheinbar wirken.","Berührung kann reichen.","Er bringt Menschen an einen anderen Ort."]},
  {name:"Quaffel",category:"Objekte",hints:["Dieser Ball gehört zu Quidditch.","Jäger werfen ihn durch Torringe.","Er ist größer als der Schnatz."]},
  {name:"Confundo",category:"Zaubersprüche",hints:["Dieser Zauberspruch beeinflusst den Kopf.","Er sorgt für Verwirrung.","Der Name klingt wie Konfusion."]},
  {name:"Nox",category:"Zaubersprüche",hints:["Dieser Zauberspruch ist sehr kurz.","Er ist das Gegenstück zu Lumos.","Er löscht Licht."]},
  {name:"Engorgio",category:"Zaubersprüche",hints:["Dieser Zauberspruch verändert Größe.","Er macht etwas größer.","Er ist das Gegenstück zu Reducio."]},
  {name:"Reducio",category:"Zaubersprüche",hints:["Dieser Zauberspruch verändert Größe.","Er macht etwas kleiner.","Er ist das Gegenstück zu Engorgio."]},
  {name:"Phönix",category:"Wesen",hints:["Dieses Wesen ist ein Vogel.","Es kann aus Asche neu entstehen.","Fawkes ist so ein Wesen."]},
  {name:"Zentaur",category:"Wesen",hints:["Dieses Wesen lebt im Verbotenen Wald.","Es verbindet Mensch und Pferd.","Firenze ist eines davon."]},
  {name:"Niffler",category:"Wesen",hints:["Dieses Wesen liebt Glitzerndes.","Es sucht Schätze.","Es kann großen Unfug anrichten."]},
  {name:"Drache",category:"Wesen",hints:["Dieses Wesen ist groß und gefährlich.","Es kann Feuer speien.","Norbert ist eines davon."]},
  {name:"Kammer des Schreckens",category:"Orte",hints:["Dieser Ort ist verborgen.","Er liegt unter Hogwarts.","Ein Basilisk lebt dort."]}
];
